---
# Droidcam

- name: Install Droidcam
  shell: |
    if [ ! -f /usr/local/bin/droidcam ]; then \
    cd /tmp/ \
    wget -O droidcam_latest.zip https://files.dev47apps.net/linux/droidcam_1.8.2.zip \
    unzip droidcam_latest.zip -d droidcam \
    cd droidcam && sudo ./install-video && sudo ./install-client; \
    fi