---

# Neovim / Workspace

- name: Install Stable Neovim
  shell: |
    cd /tmp/
    curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    chmod +x ./nvim.appimage
    mv ./nvim.appimage /usr/bin/nvim
  become: yes
