---

# Neovim / Workspace

- name: Install Stable Neovim
  shell: |
    if [ ! -f /usr/bin/nvim ]; then \
    cd /tmp/ \
    curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage \
    chmod +x ./nvim.appimage \
    mv ./nvim.appimage /usr/bin/nvim; \
    fi
  become: yes

- name: Install Vim Plug
  shell: |
    sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim' 
  become: yes

- name: Clone vim configs
  shell: |
    cd ~/.config
    mkdir nvim
    cd nvim
    git clone https://github.com/GiuseppeMP/neovim-vscodeneovim-config-files.git .
